storage:
  - mysql
  - mongodb
fetchers:
  fetch:
    - freecurrconversion
    - exchangeratesapi
  freecurrconversion:
    url: 'https://free.currconv.com/api/v7/convert'
    apiKey: 1234
    maxPerHour: 100
    maxPerRequest: 2
  exchangeratesapi:
    url: 'https://api.exchangeratesapi.io/latest'
databases:
  mysql:
    addr: 127.0.0.1:3306
    user: currency
    password: currency
    db: currencydb
    table: currency
  mongo:
    uri: mongodb://localhost:27017
    db: currencydb
    collection: currency
migrate: true
currencies:
  - EUR_RSD
  - RSD_EUR
