version: '3.4'
services:
  standalone_fetcher:
    build:
      dockerfile: ./docker/Dockerfile-fetching
      args:
        DEBUG: 0
        AFTER: 1h0m0s
    networks:
      - currency_fetcher
    volumes:
      - ./cli/currency-fetcher/config.yml:/etc/currency-fetcher/config.yml
    restart: unless-stopped
  mongo:
    image: mongo:4.4.1-bionic
    ports:
      - 27017:27017
    networks:
      - currency_fetcher
    volumes:
      - mongo_currency_fetcher:/data/db
    restart: unless-stopped
  mysql:
    image: mariadb:10.5.5-focal
    ports:
      - 3306:3306
    networks:
      - currency_fetcher
    volumes:
      - mysql_currency_fetcher:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: generate-random-password
      MYSQL_USER: currency
      MYSQL_PASSWORD: currency
      MYSQL_DATABASE: currencydb
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped
networks:
  currency_fetcher:
    driver: bridge
volumes:
  mongo_currency_fetcher:
    driver: local
  mysql_currency_fetcher:
    driver: local