version: '3.4'
services:
  mongo:
    image: mongo:4.4.1-bionic
    ports:
      - 27017:27017
    networks:
      - currency_fetcher
    volumes:
      - mongo_currency_fetcher:/data/db
    restart: unless-stopped
  mysql:
    image: mariadb:10.5.5-focal
    ports:
      - 3306:3306
    networks:
      - currency_fetcher
    volumes:
      - mysql_currency_fetcher:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: generate-random-password
      MYSQL_USER: currency
      MYSQL_PASSWORD: currency
      MYSQL_DATABASE: currencydb
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped
  standalone_fetcher:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-fetching
    networks:
      - currency_fetcher
    restart: unless-stopped
    volumes:
      - ./cli/currency-fetcher/config.yml:/currency-fetcher/config.yml
    depends_on:
      - mongo
      - mysql
    links:
      - mongo
      - mysql
    environment:
      DEBUG: 0
      AFTER: 1h0m0s
networks:
  currency_fetcher:
    driver: bridge
volumes:
  mongo_currency_fetcher:
    driver: local
  mysql_currency_fetcher:
    driver: local
  go_cache:
    driver: local
