version: '3'
vars:
  GIT_COMMIT:
    sh: git log -n 1 --format=%h
tasks:
  build-standalone-image:
    cmds:
      - docker build -t "currency_fetcher_standalone:{{.GIT_COMMIT}}" --file Dockerfile-fetching .
  build-cli-image:
    cmds:
      - docker build -t "currency_fetcher_cli:{{.GIT_COMMIT}}" --file Dockerfile-cli .
  start:
    cmds:
      - docker-compose up -d --build
  test:
    deps: [start]
    cmds:
      - docker run --rm -it -e RUNNING_IN_DOCKER=1 -e GOPATH=/go -e GO11MODULE=on
        -w /go/src/github.com/malusev998/currency-fetcher --network currency-fetcher_currency_fetcher
        -v "$(pwd):/go/src/github.com/malusev998/currency-fetcher" -v "go_cache:/go" golang:1.15 go test -race -v ./...
  fmt:
    cmds:
      - go fmt ./...
  build-executable:
    cmds:
      - go build -v -o ./dist/cli ./cli/currency-fetcher
  vet:
    cmds:
      - go vet ./...
