# syntax = docker/dockerfile:1-experimental

FROM golang:1.15 as builder

ENV GOPATH /go
ENV GO11MODULES on
ENV CGO_ENABLED=0

COPY . /go/src/github.com/malusev998/currency-fetcher
WORKDIR /go/src/github.com/malusev998/currency-fetcher/

RUN go build -v -o /build/currency-fetcher ./cli/currency-fetcher

FROM alpine:latest

COPY --from=builder /build/currency-fetcher /currency-fetcher/app
COPY ./entrypoint.sh /currency-fetcher/entrypoint.sh
ENV DEBUG=false
ENV AFTER=1h0m0s

WORKDIR /currency-fetcher
RUN chmod +x  /currency-fetcher/app
RUN chmod +x  /currency-fetcher/entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
