FROM golang:1.15 as builder

ENV GOPATH /go
ENV GO11MODULES on
ENV CGO_ENABLED=0

COPY . /go/src/github.com/malusev998/currency-fetcher
WORKDIR /go/src/github.com/malusev998/currency-fetcher/

RUN go build -v -o /build/currency-fetcher ./cli/currency-fetcher

FROM alpine:latest

RUN chmod +x /bin/currency-fetcher

COPY --from=builder /build/currency-fetcher /bin/currency-fetcher
WORKDIR /bin